version: '3.8'

services:
  web:
    build:
      context: ../boxsorter-main
      dockerfile: Dockerfile
    image: boxsorter-main
    command: gunicorn boxsorter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
      - ../boxsorter-main:/code
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=boxsorter.settings
    depends_on:
      - db
    networks:
      - internal_network
    restart: unless-stopped  # Add this line for restart policy
    stdin_open: true # Keep STDIN open
    tty: true # Allocation a pseudo-TTY
    ports:
    - "8000:8000" # Expose the service on port 8000

#  celery_worker:
#    image: boxsorter-main
#    command: celery -A boxsorter worker --loglevel=info
#    volumes:
#      - static_volume:/code/staticfiles
#      - ../boxsorter-main:/code
#    env_file:
#      - .env
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - DJANGO_SETTINGS_MODULE=boxsorter.settings
#    depends_on:
#      - db
#      - redis
#      - web
#    networks:
#      - internal_network
#    restart: unless-stopped  # Add this line for restart policy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${TI_DB_NAME}
      POSTGRES_USER: ${TI_DB_USER}
      POSTGRES_PASSWORD: ${TI_DB_PASSWORD}
    networks:
      - internal_network
    ports:
      - "5433:5432"
    restart: unless-stopped  # Add this line for restart policy

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - internal_network
#    command: ["redis-server", "--bind", "internal_network"]
#    restart: unless-stopped  # Add this line for restart policy

networks:
  internal_network:

volumes:
  static_volume:
  postgres_data: